language: python
python:
  - "3.6"
sudo: enabled
install:
  - sudo apt-get update
  # Install Conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Install dependencies
  - travis_wait 30 conda create -q -c rdkit -n test-environment python=$TRAVIS_PYTHON_VERSION rdkit
  - source activate test-environment
  - pip install coveralls
  - pip install coverage
script:
  # Install prolif
  - python setup.py install
  # Run tests with coverage
  - coverage run setup.py test
after_success:
  # Create report for coveralls
  - coveralls
